"""Add log indices

Revision ID: b5867c99f00b
Revises: 67414951c829
Create Date: 2026-06-21 14:32:30.416076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5867c99f00b'
down_revision: Union[str, Sequence[str], None] = '67414951c829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_category'), 'activity_logs', ['category'], unique=False)
    op.create_index(op.f('ix_activity_logs_date'), 'activity_logs', ['date'], unique=False)
    op.create_index(op.f('ix_activity_logs_sub_category'), 'activity_logs', ['sub_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_sub_category'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_date'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_category'), table_name='activity_logs')
    # ### end Alembic commands ###
